import { LoginPage } from './LoginPage';
export default LoginPage;

export { DashboardPage } from './DashboardPage';
export { ProductsPage } from './ProductsPage';
export { CustomersPage } from './CustomersPage';
export { InvoicesPage } from './InvoicesPage';
export { PurchasesPage } from './PurchasesPage';
export { PaymentsPage } from './PaymentsPage';
export { ReportsPage } from './ReportsPage';
export { SettingsPage } from './SettingsPage';
export { SalesPage } from './SalesPage';
export { SuppliersPage } from './SuppliersPage';
export { FarmerDashboardPage } from './FarmerDashboardPage';
export { FarmerCatalogPage } from './FarmerCatalogPage';
export { FarmerShopsPage } from './FarmerShopsPage';
export { FarmerStoresPage } from './FarmerStoresPage';
export { FarmerShopProductsPage } from './FarmerShopProductsPage';
export { FarmerStoreProductsPage } from './FarmerStoreProductsPage';
export { FarmerPurchaseHistoryPage } from './FarmerPurchaseHistoryPage';
export { FarmerStoreInvoicesPage } from './FarmerStoreInvoicesPage';
export { RegisterPage } from './RegisterPage';
export { PasswordResetPage } from './PasswordResetPage';
